/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lms.userInterface;

import com.lms.controllers.AddUser;
import com.lms.validation.*;

import java.awt.Color;
import java.util.List;

import javax.persistence.Transient;
import javax.swing.JPanel;

/**
 *
 * @author wmall
 */
public class AdminPage extends javax.swing.JFrame {
	@Transient
	private static final long serialVersionUID = 1L;
	
	/**
	 * Creates new form WelcomePage
	 */
	public AdminPage() {
		initComponents();
		setColor(btn_1);
		curr_1.setOpaque(true);
		resetColor(new JPanel[] { btn_2, btn_5 }, new JPanel[] { curr_2, curr_5 });
		jLabel1.setVisible(false);
		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(createCheckOutClerkAccountPane);
		jPanel4.repaint();
		jPanel4.revalidate();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		btn_2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		curr_2 = new javax.swing.JPanel();
		btn_1 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		curr_1 = new javax.swing.JPanel();
		btn_5 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		curr_5 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		btn_exit = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		createLibrariyanAccountPane = new javax.swing.JPanel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel36 = new javax.swing.JLabel();
		jLabel37 = new javax.swing.JLabel();
		jLabel38 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		cnic = new javax.swing.JTextField();
		phone = new javax.swing.JTextField();
		city = new javax.swing.JTextField();
		email = new javax.swing.JTextField();
		address = new javax.swing.JTextField();
		password = new javax.swing.JTextField();
		createLibrariyanButton = new javax.swing.JButton();
		gender = new javax.swing.JComboBox();
		librariyanMessageLabel = new javax.swing.JLabel();
		createCheckOutClerkAccountPane = new javax.swing.JPanel();
		jLabel39 = new javax.swing.JLabel();
		nameClerk = new javax.swing.JLabel();
		genderClerk = new javax.swing.JLabel();
		cnicClerk = new javax.swing.JLabel();
		phoneClerk = new javax.swing.JLabel();
		addressClerk = new javax.swing.JLabel();
		cityClerk = new javax.swing.JLabel();
		emailClerk = new javax.swing.JLabel();
		passwordClerk = new javax.swing.JLabel();
		nameBox = new javax.swing.JTextField();
		cnicBox = new javax.swing.JTextField();
		phoneBox = new javax.swing.JTextField();
		cityBox = new javax.swing.JTextField();
		emailBox = new javax.swing.JTextField();
		addressBox = new javax.swing.JTextField();
		passwordBox = new javax.swing.JTextField();
		createClerkButton = new javax.swing.JButton();
		genderComboBox = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setUndecorated(true);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel3.setBackground(new java.awt.Color(0, 37, 63));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		btn_2.setBackground(new java.awt.Color(0, 37, 45));
		btn_2.setForeground(new java.awt.Color(255, 255, 255));
		btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_2MouseClicked(evt);
			}

			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_2MousePressed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 255, 255));
		jLabel5.setText("Log Out");

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Manager_25px.png"))); // NOI18N

		curr_2.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_2Layout = new javax.swing.GroupLayout(curr_2);
		curr_2.setLayout(curr_2Layout);
		curr_2Layout.setHorizontalGroup(curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_2Layout.setVerticalGroup(curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
		btn_2.setLayout(btn_2Layout);
		btn_2Layout
				.setHorizontalGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_2Layout.createSequentialGroup()
								.addComponent(curr_2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel6)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel5).addContainerGap(181, Short.MAX_VALUE)));
		btn_2Layout.setVerticalGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_2Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel6).addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 60));

		btn_1.setBackground(new java.awt.Color(0, 37, 45));
		btn_1.setForeground(new java.awt.Color(255, 255, 255));
		btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_1MousePressed(evt);
			}
		});

		jLabel15.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("Create Clerk Acoount");

		jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Front Desk_25px.png"))); // NOI18N

		curr_1.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_1Layout = new javax.swing.GroupLayout(curr_1);
		curr_1.setLayout(curr_1Layout);
		curr_1Layout.setHorizontalGroup(curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_1Layout.setVerticalGroup(curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
		btn_1.setLayout(btn_1Layout);
		btn_1Layout
				.setHorizontalGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1Layout.createSequentialGroup()
								.addComponent(curr_1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel16).addGap(18, 18, 18).addComponent(jLabel15)
								.addContainerGap(74, Short.MAX_VALUE)));
		btn_1Layout.setVerticalGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_1Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel16).addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 60));

		btn_5.setBackground(new java.awt.Color(0, 37, 45));
		btn_5.setForeground(new java.awt.Color(255, 255, 255));
		btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_5MousePressed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Create Librariyan Account");

		jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Manager_25px.png"))); // NOI18N

		curr_5.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_5Layout = new javax.swing.GroupLayout(curr_5);
		curr_5.setLayout(curr_5Layout);
		curr_5Layout.setHorizontalGroup(curr_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_5Layout.setVerticalGroup(curr_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
		btn_5.setLayout(btn_5Layout);
		btn_5Layout
				.setHorizontalGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_5Layout.createSequentialGroup()
								.addComponent(curr_5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel12)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel11).addContainerGap(44, Short.MAX_VALUE)));
		btn_5Layout.setVerticalGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_5Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel12).addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 60));

		getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

		jPanel1.setBackground(new java.awt.Color(2, 91, 131));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel2.setBackground(new java.awt.Color(2, 91, 110));
		jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				jPanel2MouseDragged(evt);
			}
		});
		jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jPanel2MousePressed(evt);
			}
		});

		btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Cancel_22px.png"))); // NOI18N
		btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_exitMousePressed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(748, Short.MAX_VALUE).addComponent(btn_exit).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btn_exit).addContainerGap()));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

		jPanel4.setBackground(new java.awt.Color(0, 37, 63));
		jPanel4.setLayout(new java.awt.CardLayout());

		createLibrariyanAccountPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel18.setFont(new java.awt.Font("SketchFlow Print", 0, 24)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("Create Librariyan Account");

		jLabel19.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel19.setForeground(new java.awt.Color(255, 255, 255));
		jLabel19.setText("Name");

		jLabel20.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel20.setForeground(new java.awt.Color(255, 255, 255));
		jLabel20.setText("Gender");

		jLabel21.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel21.setForeground(new java.awt.Color(255, 255, 255));
		jLabel21.setText("CNIC");

		jLabel22.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel22.setForeground(new java.awt.Color(255, 255, 255));
		jLabel22.setText("Phone");

		jLabel23.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("Address");

		jLabel36.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel36.setForeground(new java.awt.Color(255, 255, 255));
		jLabel36.setText("City");

		jLabel37.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel37.setForeground(new java.awt.Color(255, 255, 255));
		jLabel37.setText("Email");

		jLabel38.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		jLabel38.setForeground(new java.awt.Color(255, 255, 255));
		jLabel38.setText("Password");

		name.setBackground(new java.awt.Color(2, 91, 133));
		name.setForeground(new java.awt.Color(255, 255, 255));
		name.setToolTipText("");
		name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		name.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//nameActionPerformed(evt);
			}
		});

		cnic.setBackground(new java.awt.Color(2, 91, 133));
		cnic.setForeground(new java.awt.Color(255, 255, 255));
		cnic.setToolTipText("");
		cnic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		cnic.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//cnicActionPerformed(evt);
			}
		});

		phone.setBackground(new java.awt.Color(2, 91, 133));
		phone.setForeground(new java.awt.Color(255, 255, 255));
		phone.setToolTipText("");
		phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		phone.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//phoneActionPerformed(evt);
			}
		});

		city.setBackground(new java.awt.Color(2, 91, 133));
		city.setForeground(new java.awt.Color(255, 255, 255));
		city.setToolTipText("");
		city.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		city.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//cityActionPerformed(evt);
			}
		});

		email.setBackground(new java.awt.Color(2, 91, 133));
		email.setForeground(new java.awt.Color(255, 255, 255));
		email.setToolTipText("");
		email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		email.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailActionPerformed(evt);
			}
		});

		address.setBackground(new java.awt.Color(2, 91, 133));
		address.setForeground(new java.awt.Color(255, 255, 255));
		address.setToolTipText("");
		address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		address.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//addressActionPerformed(evt);
			}
		});

		password.setBackground(new java.awt.Color(2, 91, 133));
		password.setForeground(new java.awt.Color(255, 255, 255));
		password.setToolTipText("");
		password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		password.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//passwordActionPerformed(evt);
			}
		});

		createLibrariyanButton.setBackground(new java.awt.Color(2, 91, 133));
		createLibrariyanButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		createLibrariyanButton.setForeground(new java.awt.Color(255, 255, 255));
		createLibrariyanButton.setText("Create Account");
		createLibrariyanButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createLibrariyanButtonActionPerformed(evt);
			}
		});

		gender.setBackground(new java.awt.Color(2, 91, 133));
		gender.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));

		librariyanMessageLabel.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		librariyanMessageLabel.setForeground(new java.awt.Color(255, 51, 51));
		librariyanMessageLabel.setText("jLabel1");

		javax.swing.GroupLayout createLibrariyanAccountPaneLayout = new javax.swing.GroupLayout(
				createLibrariyanAccountPane);
		createLibrariyanAccountPane.setLayout(createLibrariyanAccountPaneLayout);
		createLibrariyanAccountPaneLayout
				.setHorizontalGroup(createLibrariyanAccountPaneLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								createLibrariyanAccountPaneLayout.createSequentialGroup().addGap(22, 22, 22)
										.addGroup(
												createLibrariyanAccountPaneLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE,
																89, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel21)
														.addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE,
																49, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE,
																70, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														name, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54,
												Short.MAX_VALUE)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														createLibrariyanAccountPaneLayout
																.createSequentialGroup()
																.addComponent(
																		jLabel20,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
												.addGroup(createLibrariyanAccountPaneLayout.createSequentialGroup()
														.addGroup(createLibrariyanAccountPaneLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel36)
																.addComponent(jLabel22,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 54,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel38,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(10, 10, 10)))
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(24, 24, 24))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								createLibrariyanAccountPaneLayout.createSequentialGroup()
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(createLibrariyanButton, javax.swing.GroupLayout.PREFERRED_SIZE,
												289, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(227, 227, 227))
						.addGroup(createLibrariyanAccountPaneLayout.createSequentialGroup()
								.addGroup(createLibrariyanAccountPaneLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(createLibrariyanAccountPaneLayout.createSequentialGroup()
												.addGap(231, 231, 231).addComponent(jLabel18))
										.addGroup(createLibrariyanAccountPaneLayout.createSequentialGroup()
												.addGap(267, 267, 267).addComponent(librariyanMessageLabel)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		createLibrariyanAccountPaneLayout
				.setVerticalGroup(
						createLibrariyanAccountPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(createLibrariyanAccountPaneLayout.createSequentialGroup().addGap(36, 36, 36)
										.addComponent(jLabel18)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(librariyanMessageLabel).addGap(30, 30, 30)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel19).addComponent(jLabel20)
												.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(59, 59, 59)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel21).addComponent(jLabel22)
												.addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(67, 67, 67)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel23).addComponent(jLabel36)
												.addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(75, 75, 75)
										.addGroup(createLibrariyanAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel37).addComponent(jLabel38)
												.addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
												Short.MAX_VALUE)
										.addComponent(createLibrariyanButton, javax.swing.GroupLayout.PREFERRED_SIZE,
												39, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(63, 63, 63)));

		jPanel4.add(createLibrariyanAccountPane, "card2");

		createCheckOutClerkAccountPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel39.setFont(new java.awt.Font("SketchFlow Print", 0, 24)); // NOI18N
		jLabel39.setForeground(new java.awt.Color(255, 255, 255));
		jLabel39.setText("Create Check Out Clerk Account");

		nameClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		nameClerk.setForeground(new java.awt.Color(255, 255, 255));
		nameClerk.setText("Name");

		genderClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		genderClerk.setForeground(new java.awt.Color(255, 255, 255));
		genderClerk.setText("Gender");

		cnicClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		cnicClerk.setForeground(new java.awt.Color(255, 255, 255));
		cnicClerk.setText("CNIC");

		phoneClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		phoneClerk.setForeground(new java.awt.Color(255, 255, 255));
		phoneClerk.setText("Phone");

		addressClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		addressClerk.setForeground(new java.awt.Color(255, 255, 255));
		addressClerk.setText("Address");

		cityClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		cityClerk.setForeground(new java.awt.Color(255, 255, 255));
		cityClerk.setText("City");

		emailClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		emailClerk.setForeground(new java.awt.Color(255, 255, 255));
		emailClerk.setText("Email");

		passwordClerk.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
		passwordClerk.setForeground(new java.awt.Color(255, 255, 255));
		passwordClerk.setText("Password");

		nameBox.setBackground(new java.awt.Color(2, 91, 133));
		nameBox.setForeground(new java.awt.Color(255, 255, 255));
		nameBox.setToolTipText("");
		nameBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		nameBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//nameBoxActionPerformed(evt);
			}
		});

		cnicBox.setBackground(new java.awt.Color(2, 91, 133));
		cnicBox.setForeground(new java.awt.Color(255, 255, 255));
		cnicBox.setToolTipText("");
		cnicBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		cnicBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//cnicBoxActionPerformed(evt);
			}
		});

		phoneBox.setBackground(new java.awt.Color(2, 91, 133));
		phoneBox.setForeground(new java.awt.Color(255, 255, 255));
		phoneBox.setToolTipText("");
		phoneBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		phoneBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//phoneBoxActionPerformed(evt);
			}
		});

		cityBox.setBackground(new java.awt.Color(2, 91, 133));
		cityBox.setForeground(new java.awt.Color(255, 255, 255));
		cityBox.setToolTipText("");
		cityBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		cityBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//cityBoxActionPerformed(evt);
			}
		});

		emailBox.setBackground(new java.awt.Color(2, 91, 133));
		emailBox.setForeground(new java.awt.Color(255, 255, 255));
		emailBox.setToolTipText("");
		emailBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		emailBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailBoxActionPerformed(evt);
			}
		});

		addressBox.setBackground(new java.awt.Color(2, 91, 133));
		addressBox.setForeground(new java.awt.Color(255, 255, 255));
		addressBox.setToolTipText("");
		addressBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		addressBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//addressBoxActionPerformed(evt);
			}
		});

		passwordBox.setBackground(new java.awt.Color(2, 91, 133));
		passwordBox.setForeground(new java.awt.Color(255, 255, 255));
		passwordBox.setToolTipText("");
		passwordBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		passwordBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//passwordBoxActionPerformed(evt);
			}
		});

		createClerkButton.setBackground(new java.awt.Color(2, 91, 133));
		createClerkButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		createClerkButton.setForeground(new java.awt.Color(255, 255, 255));
		createClerkButton.setText("Create Account");
		createClerkButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createClerkButtonActionPerformed(evt);
			}
		});

		genderComboBox.setBackground(new java.awt.Color(2, 91, 133));
		genderComboBox.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));

		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("jLabel1");

		javax.swing.GroupLayout createCheckOutClerkAccountPaneLayout = new javax.swing.GroupLayout(
				createCheckOutClerkAccountPane);
		createCheckOutClerkAccountPane.setLayout(createCheckOutClerkAccountPaneLayout);
		createCheckOutClerkAccountPaneLayout.setHorizontalGroup(createCheckOutClerkAccountPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(createCheckOutClerkAccountPaneLayout.createSequentialGroup().addGap(22, 22, 22)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(nameClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cnicClerk)
								.addComponent(emailClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(addressClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cnicBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										createCheckOutClerkAccountPaneLayout.createSequentialGroup()
												.addComponent(genderClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
								.addGroup(createCheckOutClerkAccountPaneLayout.createSequentialGroup()
										.addGroup(createCheckOutClerkAccountPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(cityClerk)
												.addComponent(phoneClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 54,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(passwordClerk, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(10, 10, 10)))
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(phoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(24, 24, 24))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCheckOutClerkAccountPaneLayout
						.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										createCheckOutClerkAccountPaneLayout.createSequentialGroup()
												.addComponent(createClerkButton, javax.swing.GroupLayout.PREFERRED_SIZE,
														289, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(227, 227, 227))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										createCheckOutClerkAccountPaneLayout.createSequentialGroup()
												.addComponent(jLabel39).addGap(197, 197, 197))))
				.addGroup(createCheckOutClerkAccountPaneLayout.createSequentialGroup().addGap(224, 224, 224)
						.addComponent(jLabel1).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		createCheckOutClerkAccountPaneLayout.setVerticalGroup(createCheckOutClerkAccountPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(createCheckOutClerkAccountPaneLayout.createSequentialGroup().addGap(34, 34, 34)
						.addComponent(jLabel39).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel1).addGap(27, 27, 27)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(nameClerk)
								.addComponent(genderClerk)
								.addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(59, 59, 59)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(cnicClerk)
								.addComponent(phoneClerk)
								.addComponent(cnicBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(phoneBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(67, 67, 67)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(addressClerk).addComponent(cityClerk)
								.addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(75, 75, 75)
						.addGroup(createCheckOutClerkAccountPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(emailClerk).addComponent(passwordClerk)
								.addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
						.addComponent(createClerkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(63, 63, 63)));

		jPanel4.add(createCheckOutClerkAccountPane, "card2");

		jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 580));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 780, 620));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	int xx, xy;

	private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel2MouseDragged
		// TODO add your handling code here:

		// source to drag
		int x = evt.getXOnScreen();
		int y = evt.getYOnScreen();
		this.setLocation(x - xx, y - xy);
	}// GEN-LAST:event_jPanel2MouseDragged

	private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel2MousePressed
		// TODO add your handling code here:

		// drag this pane
		xx = evt.getX();
		xy = evt.getY();
	}// GEN-LAST:event_jPanel2MousePressed

	private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_exitMousePressed
		// TODO add your handling code here:
		// exit button
		System.exit(0);
	}// GEN-LAST:event_btn_exitMousePressed

	private void btn_1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_1MousePressed
		// TODO add your handling code here:
		setColor(btn_1);
		curr_1.setOpaque(true);
		resetColor(new JPanel[] { btn_2, btn_5 }, new JPanel[] { curr_2, curr_5 });
		jLabel1.setVisible(false);
		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(createCheckOutClerkAccountPane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_1MousePressed

	private void btn_2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_2MousePressed
		// TODO add your handling code here:

		setColor(btn_2);
		curr_2.setOpaque(true);
		resetColor(new JPanel[] { btn_1, btn_5 }, new JPanel[] { curr_1, curr_5 });
		librariyanMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(createLibrariyanAccountPane);
		jPanel4.repaint();
		jPanel4.revalidate();
	}// GEN-LAST:event_btn_2MousePressed

	private void createLibrariyanButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createLibrariyanButtonActionPerformed

		String nameLibrariyan = null;
		String cnicLibrariyan = null;
		String emailLibrariyan = null;
		String addressLibrariyan = null;
		String genderLibrariyan = null;
		String phoneLibrariyan = null;
		String passwordLibrariyan = null;
		String cityLibrariyan = null;
		List users = null;
		try {
			nameLibrariyan = name.getText();
			cnicLibrariyan = cnic.getText();
			emailLibrariyan = email.getText();
			addressLibrariyan = address.getText();
			genderLibrariyan = (String) gender.getSelectedItem();
			phoneLibrariyan = phone.getText();
			passwordLibrariyan = password.getText();
			cityLibrariyan = city.getText();

			String msg = InputValidation.validate(nameLibrariyan, genderLibrariyan, cnicLibrariyan, phoneLibrariyan,
					addressLibrariyan, cityLibrariyan, emailLibrariyan, passwordLibrariyan);
			if (!msg.equals("1")) {
				librariyanMessageLabel.setText(msg);
				librariyanMessageLabel.setVisible(true);
				return;
			}

			if (!CnicValidation.validate(cnicLibrariyan)) {
				librariyanMessageLabel.setText("Invalid CNIC. It should be of exactly 13 integers");
				librariyanMessageLabel.setVisible(true);
				return;

			}

			if (!EmailValidation.validate(emailLibrariyan)) {
				librariyanMessageLabel.setText("Invalid Email address");
				librariyanMessageLabel.setVisible(true);
				return;

			}

			if (!PhoneValidation.validate(phoneLibrariyan)) {
				librariyanMessageLabel.setText("Invalid Phone Number. It should be of Integers of 7 < length < 13");
				librariyanMessageLabel.setVisible(true);
				return;

			}

			msg = ExistenseValidation.validate(emailLibrariyan, cnicLibrariyan);

			if (!msg.equals("1")) {
				librariyanMessageLabel.setText(msg);
				librariyanMessageLabel.setVisible(true);
				return;

			}

			AddUser librariyanObject = new AddUser();

			boolean flag = librariyanObject.addLmsuser(nameLibrariyan, genderLibrariyan, cnicLibrariyan,
					phoneLibrariyan, addressLibrariyan, cityLibrariyan, emailLibrariyan, passwordLibrariyan,
					"librariyan");
			if (flag) {
				librariyanMessageLabel.setText(" user created");

				librariyanMessageLabel.setVisible(true);

				name.setText("");
				cnic.setText("");
				email.setText("");
				address.setText("");

				phone.setText("");
				password.setText("");
				city.setText("");

			} else {
				librariyanMessageLabel.setText("Error While Creating the user.");
				librariyanMessageLabel.setVisible(true);

			}

		} catch (Exception e) {

			librariyanMessageLabel.setText("Unable to create User Account");
			librariyanMessageLabel.setVisible(true);

		}

	}// GEN-LAST:event_createLibrariyanButtonActionPerformed

	private void createClerkButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createClerkButtonActionPerformed

		String nameClerk = null;
		String cnicClerk = null;
		String emailClerk = null;
		String addressClerk = null;
		String genderClerk = null;
		String phoneClerk = null;
		String passwordClerk = null;
		String cityClerk = null;
		List users = null;
		try {
			nameClerk = nameBox.getText();
			cnicClerk = cnicBox.getText();
			emailClerk = emailBox.getText();
			addressClerk = addressBox.getText();
			genderClerk = (String) genderComboBox.getSelectedItem();
			phoneClerk = phoneBox.getText();
			passwordClerk = passwordBox.getText();
			cityClerk = cityBox.getText();

			String msg = InputValidation.validate(nameClerk, genderClerk, cnicClerk, phoneClerk, addressClerk,
					cityClerk, emailClerk, passwordClerk);
			if (!msg.equals("1")) {
				jLabel1.setText(msg);
				jLabel1.setVisible(true);
				return;
			}

			if (!CnicValidation.validate(cnicClerk)) {
				jLabel1.setText("Invalid CNIC. It should be of exactly 13 integers");
				jLabel1.setVisible(true);
				return;

			}

			if (!EmailValidation.validate(emailClerk)) {
				jLabel1.setText("Invalid Email address");
				jLabel1.setVisible(true);
				return;

			}

			if (!PhoneValidation.validate(phoneClerk)) {
				jLabel1.setText("Invalid Phone Number. It should be of Integers of 7 < length < 13");
				jLabel1.setVisible(true);
				return;

			}

			msg = ExistenseValidation.validate(emailClerk, cnicClerk);

			if (!msg.equals("1")) {
				jLabel1.setText(msg);
				jLabel1.setVisible(true);
				return;

			}

			AddUser clerkObject = new AddUser();

			boolean flag = clerkObject.addLmsuser(nameClerk, genderClerk, cnicClerk, phoneClerk, addressClerk,
					cityClerk, emailClerk, passwordClerk, "clerk");
			if (flag) {
				jLabel1.setText(" user created");
				jLabel1.setVisible(true);

				nameBox.setText("");
				cnicBox.setText("");
				emailBox.setText("");
				addressBox.setText("");

				phoneBox.setText("");
				passwordBox.setText("");
				cityBox.setText("");

			} else {
				jLabel1.setText("Error While Creating the user.");
				jLabel1.setVisible(true);

			}

		} catch (Exception e) {

			jLabel1.setText("Unable to create User Account");
			jLabel1.setVisible(true);

		}

	}// GEN-LAST:event_createClerkButtonActionPerformed

	private void btn_5MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_5MousePressed
		// TODO add your handling code here:

		setColor(btn_5);
		curr_5.setOpaque(true);
		resetColor(new JPanel[] { btn_1, btn_2 }, new JPanel[] { curr_1, curr_2 });
		librariyanMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(createLibrariyanAccountPane);
		jPanel4.repaint();
		jPanel4.revalidate();
	}// GEN-LAST:event_btn_5MousePressed

	private void btn_2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_2MouseClicked
		// TODO add your handling code here:
		this.dispose();
		new WelcomePage().setVisible(true);

	}// GEN-LAST:event_btn_2MouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new AdminPage().setVisible(true);
			}
		});
	}

	private void setColor(JPanel pane) {
		pane.setBackground(new Color(41, 57, 80));

	}

	private void resetColor(JPanel[] pane, JPanel[] indicators) {

		for (int i = 0; i < pane.length; i++) {
			pane[i].setBackground(new Color(23, 35, 51));
		}

		for (int i = 0; i < indicators.length; i++) {
			indicators[i].setOpaque(false);
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField address;
	private javax.swing.JTextField addressBox;
	private javax.swing.JLabel addressClerk;
	private javax.swing.JPanel btn_1;
	private javax.swing.JPanel btn_2;
	private javax.swing.JPanel btn_3;
	private javax.swing.JPanel btn_4;
	private javax.swing.JPanel btn_5;
	private javax.swing.JLabel btn_exit;
	private javax.swing.JTextField city;
	private javax.swing.JTextField cityBox;
	private javax.swing.JLabel cityClerk;
	private javax.swing.JTextField cnic;
	private javax.swing.JTextField cnicBox;
	private javax.swing.JLabel cnicClerk;
	private javax.swing.JPanel createCheckOutClerkAccountPane;
	private javax.swing.JButton createClerkButton;
	private javax.swing.JPanel createLibrariyanAccountPane;
	private javax.swing.JButton createLibrariyanButton;
	private javax.swing.JPanel curr_1;
	private javax.swing.JPanel curr_2;
	private javax.swing.JPanel curr_3;
	private javax.swing.JPanel curr_4;
	private javax.swing.JPanel curr_5;
	private javax.swing.JTextField email;
	private javax.swing.JTextField emailBox;
	private javax.swing.JLabel emailClerk;
	private javax.swing.JComboBox gender;
	private javax.swing.JLabel genderClerk;
	private javax.swing.JComboBox genderComboBox;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel36;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JLabel librariyanMessageLabel;
	private javax.swing.JTextField name;
	private javax.swing.JTextField nameBox;
	private javax.swing.JLabel nameClerk;
	private javax.swing.JTextField password;
	private javax.swing.JTextField passwordBox;
	private javax.swing.JLabel passwordClerk;
	private javax.swing.JTextField phone;
	private javax.swing.JTextField phoneBox;
	private javax.swing.JLabel phoneClerk;
	// End of variables declaration//GEN-END:variables
}
