/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lms.userInterface;

import com.lms.controllers.BookQueries;
import com.lms.controllers.HoldBookFunctions;
import com.lms.controllers.LmsuserQueries;
import com.lms.controllers.LoanQueries;
import com.lms.modals.*;


import java.awt.Color;
import java.util.List;

import javax.persistence.Transient;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import com.lms.service.*;

/**
 *
 * @author wmall
 */
public class BorrowerPage extends javax.swing.JFrame {

	@Transient
	private static final long serialVersionUID = 1L;
    /**
     * Creates new form WelcomePage
     */
    public BorrowerPage() {
        initComponents();
        setColor(btn_1);
        curr_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2, btn_3}, new JPanel[]{curr_2, curr_3});

        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(searchPane);
        jPanel4.repaint();
        jPanel4.revalidate();
        
        searchMessageLabel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btn_3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        curr_3 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        curr_1 = new javax.swing.JPanel();
        btn_2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        curr_2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        personelInfoPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        cnicPersonelInfo = new javax.swing.JLabel();
        namePersonelInfo = new javax.swing.JLabel();
        addressPersonelInfo = new javax.swing.JLabel();
        emailPersonelInfo = new javax.swing.JLabel();
        genderPersonelInfo = new javax.swing.JLabel();
        phonePersonelInfo = new javax.swing.JLabel();
        cityPersonelInfo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        borrowedBooksTable = new javax.swing.JTable();
        searchPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        searchBookLibrariyan = new javax.swing.JTextField();
        searchByCombo = new javax.swing.JComboBox();
        searchBookButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        librariyanSearchBooksTable = new javax.swing.JTable();
        searchMessageLabel = new javax.swing.JLabel();
        ReserveBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 37, 63));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_3.setBackground(new java.awt.Color(0, 37, 45));
        btn_3.setForeground(new java.awt.Color(255, 255, 255));
        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_3MousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Logout");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Logout Rounded Left_25px.png"))); // NOI18N

        curr_3.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout curr_3Layout = new javax.swing.GroupLayout(curr_3);
        curr_3.setLayout(curr_3Layout);
        curr_3Layout.setHorizontalGroup(
            curr_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        curr_3Layout.setVerticalGroup(
            curr_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
        btn_3.setLayout(btn_3Layout);
        btn_3Layout.setHorizontalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_3Layout.createSequentialGroup()
                .addComponent(curr_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        btn_3Layout.setVerticalGroup(
            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curr_3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(btn_3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 60));

        btn_1.setBackground(new java.awt.Color(0, 37, 45));
        btn_1.setForeground(new java.awt.Color(255, 255, 255));
        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_1MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Search");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Search_25px.png"))); // NOI18N

        curr_1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout curr_1Layout = new javax.swing.GroupLayout(curr_1);
        curr_1.setLayout(curr_1Layout);
        curr_1Layout.setHorizontalGroup(
            curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        curr_1Layout.setVerticalGroup(
            curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
        btn_1.setLayout(btn_1Layout);
        btn_1Layout.setHorizontalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1Layout.createSequentialGroup()
                .addComponent(curr_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        btn_1Layout.setVerticalGroup(
            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curr_1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(btn_1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 60));

        btn_2.setBackground(new java.awt.Color(0, 37, 45));
        btn_2.setForeground(new java.awt.Color(255, 255, 255));
        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_2MousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Personel Information");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/More Info_25px.png"))); // NOI18N

        curr_2.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout curr_2Layout = new javax.swing.GroupLayout(curr_2);
        curr_2.setLayout(curr_2Layout);
        curr_2Layout.setHorizontalGroup(
            curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        curr_2Layout.setVerticalGroup(
            curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
        btn_2.setLayout(btn_2Layout);
        btn_2Layout.setHorizontalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_2Layout.createSequentialGroup()
                .addComponent(curr_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        btn_2Layout.setVerticalGroup(
            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(curr_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addGroup(btn_2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

        jPanel1.setBackground(new java.awt.Color(2, 91, 131));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(2, 91, 110));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Cancel_22px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(748, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        jPanel4.setBackground(new java.awt.Color(0, 37, 63));
        jPanel4.setLayout(new java.awt.CardLayout());

        personelInfoPane.setBackground(new java.awt.Color(2, 91, 133));

        jPanel6.setBackground(new java.awt.Color(2, 91, 133));

        jLabel19.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("First Name");

        jLabel21.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CNIC");

        jLabel23.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Address");

        jLabel37.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Email");

        jLabel20.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Gender");

        jLabel22.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Phone");

        jLabel36.setFont(new java.awt.Font("SketchFlow Print", 2, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("City");

        cnicPersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        cnicPersonelInfo.setText("jLabel2");

        namePersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        namePersonelInfo.setText("jLabel1");

        addressPersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        addressPersonelInfo.setText("jLabel3");

        emailPersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        emailPersonelInfo.setText("jLabel4");

        genderPersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        genderPersonelInfo.setText("jLabel9");

        phonePersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        phonePersonelInfo.setText("jLabel10");

        cityPersonelInfo.setForeground(new java.awt.Color(255, 255, 255));
        cityPersonelInfo.setText("jLabel11");

        borrowedBooksTable.setAutoCreateRowSorter(true);
        borrowedBooksTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        borrowedBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(borrowedBooksTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(namePersonelInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(cnicPersonelInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(emailPersonelInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel36)
                                        .addGap(115, 115, 115)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityPersonelInfo)
                                    .addComponent(phonePersonelInfo)
                                    .addComponent(genderPersonelInfo))
                                .addGap(172, 172, 172))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(addressPersonelInfo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(namePersonelInfo)
                    .addComponent(genderPersonelInfo))
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(cnicPersonelInfo)
                    .addComponent(phonePersonelInfo))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cityPersonelInfo)
                    .addComponent(jLabel37)
                    .addComponent(emailPersonelInfo))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(addressPersonelInfo))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(139, 139, 139))
        );

        jScrollPane2.setViewportView(jPanel6);

        javax.swing.GroupLayout personelInfoPaneLayout = new javax.swing.GroupLayout(personelInfoPane);
        personelInfoPane.setLayout(personelInfoPaneLayout);
        personelInfoPaneLayout.setHorizontalGroup(
            personelInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        personelInfoPaneLayout.setVerticalGroup(
            personelInfoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jPanel4.add(personelInfoPane, "card2");

        searchPane.setBackground(new java.awt.Color(2, 91, 133));

        jPanel5.setBackground(new java.awt.Color(2, 91, 133));
        jPanel5.setPreferredSize(new java.awt.Dimension(750, 540));

        searchBookLibrariyan.setBackground(new java.awt.Color(2, 91, 133));
        searchBookLibrariyan.setForeground(new java.awt.Color(255, 255, 255));
        searchBookLibrariyan.setToolTipText("");
        searchBookLibrariyan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        searchBookLibrariyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookLibrariyanActionPerformed(evt);
            }
        });

        searchByCombo.setBackground(new java.awt.Color(2, 91, 133));
        searchByCombo.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
        searchByCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By Title", "By Author", "By Subject" }));

        searchBookButton.setBackground(new java.awt.Color(2, 91, 133));
        searchBookButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        searchBookButton.setForeground(new java.awt.Color(255, 255, 255));
        searchBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Search_25px.png"))); // NOI18N
        searchBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBookButtonActionPerformed(evt);
            }
        });

        librariyanSearchBooksTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        librariyanSearchBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Subject", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(librariyanSearchBooksTable);

        searchMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
        searchMessageLabel.setText("jLabel1");

        ReserveBook.setBackground(new java.awt.Color(2, 91, 133));
        ReserveBook.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
        ReserveBook.setForeground(new java.awt.Color(255, 255, 255));
        ReserveBook.setText("Reserve Book");
        ReserveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(searchMessageLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(searchBookLibrariyan, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(searchByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(381, 381, 381))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(ReserveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(searchMessageLabel)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBookLibrariyan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(searchBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(ReserveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout searchPaneLayout = new javax.swing.GroupLayout(searchPane);
        searchPane.setLayout(searchPaneLayout);
        searchPaneLayout.setHorizontalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        searchPaneLayout.setVerticalGroup(
            searchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        jPanel4.add(searchPane, "card2");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 780, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xx, xy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:

        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        // exit button
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
        // TODO add your handling code here:
        setColor(btn_1);
        curr_1.setOpaque(true);
        resetColor(new JPanel[]{btn_2, btn_3}, new JPanel[]{curr_2, curr_3});

        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(searchPane);
        jPanel4.repaint();
        jPanel4.revalidate();

    }//GEN-LAST:event_btn_1MousePressed

    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
        // TODO add your handling code here:

        this.dispose();
        new WelcomePage().setVisible(true);

    }//GEN-LAST:event_btn_3MousePressed

    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
        // TODO add your handling code here:

        setColor(btn_2);
        curr_2.setOpaque(true);
        resetColor(new JPanel[]{btn_1, btn_3}, new JPanel[]{curr_1, curr_3});

        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();

        jPanel4.add(personelInfoPane);
        jPanel4.repaint();
        jPanel4.revalidate();
        
        searchMessageLabel.setVisible(false);
        
        LmsuserQueries userObject = new LmsuserQueries();
        Lmsuser userList = userObject.findByEmail(SessionService.getInstance());
        
        int userId = userList.getId();
        
        Lmsuser userListLocal = userObject.findById(userId);
        
        
        namePersonelInfo.setText(userListLocal.getUsername());
        cnicPersonelInfo.setText(userListLocal.getCnic());
        emailPersonelInfo.setText(userListLocal.getEmail());
        addressPersonelInfo.setText(userListLocal.getAddress());
        phonePersonelInfo.setText(userListLocal.getPhone());
        cityPersonelInfo.setText(userListLocal.getCity());       
        genderPersonelInfo.setText(userListLocal.getGender());
          
        LoanQueries l1 = new LoanQueries();
        List<Loan> loanListLocal = l1.findBooksBorrowed(userListLocal);
        
         DefaultTableModel model = (DefaultTableModel) borrowedBooksTable.getModel();

            int rowCount = model.getRowCount();
            

            Object rowData[] = new Object[4];

            for (int i = 0; i < loanListLocal.size(); i++) {

                rowData[0] = loanListLocal.get(i).getBookid().getIsbn();
                rowData[1] = loanListLocal.get(i).getBookid().getTitle();
                rowData[2] = loanListLocal.get(i).getBookid().getAuthor();
                rowData[3] = loanListLocal.get(i).getBookid().getBooksubject();
               
                model.addRow(rowData);

            }
        
    }//GEN-LAST:event_btn_2MousePressed

    private void searchBookLibrariyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookLibrariyanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBookLibrariyanActionPerformed

    private void searchBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBookButtonActionPerformed

        String searchText = null;
        String searchBy = null;

        try {

            searchText = searchBookLibrariyan.getText();
            searchBy = (String) searchByCombo.getSelectedItem();

            if (searchText.equals("")) {

                searchMessageLabel.setText("Please Enter Text");
                searchMessageLabel.setVisible(true);
                return;
            }

            BookQueries b1 = new BookQueries();
            List<Book> bookList = null;
            if (searchBy.equalsIgnoreCase("by title")) {

                bookList = b1.findByTitle(searchText);

            } else if (searchBy.equalsIgnoreCase("by author")) {
                bookList = b1.findByAuthor(searchText);

            } else if (searchBy.equalsIgnoreCase("by subject")) {
                bookList = b1.findBySubject(searchText);

            }

            if (bookList.isEmpty()) {
                searchMessageLabel.setText("No Record Found");
                searchMessageLabel.setVisible(true);
                return;

            }

            DefaultTableModel model = (DefaultTableModel) librariyanSearchBooksTable.getModel();

            int rowCount = model.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                model.removeRow(i);
            }

            Object rowData[] = new Object[5];

            for (int i = 0; i < bookList.size(); i++) {

                rowData[0] = bookList.get(i).getIsbn();
                rowData[1] = bookList.get(i).getTitle();
                rowData[2] = bookList.get(i).getAuthor();
                rowData[3] = bookList.get(i).getBooksubject();
                rowData[4] = bookList.get(i).getAvailability();
                model.addRow(rowData);

            }

        } catch (Exception e) {

            searchMessageLabel.setText("Unable to Show Records");
            searchMessageLabel.setVisible(true);

        }

    }//GEN-LAST:event_searchBookButtonActionPerformed

    private void ReserveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveBookActionPerformed

        try {
            DefaultTableModel model = (DefaultTableModel) librariyanSearchBooksTable.getModel();
            int selectedRowIndex = librariyanSearchBooksTable.getSelectedRow();

            String isbnObject = model.getValueAt(selectedRowIndex, 0).toString();

            BookQueries b1 = new BookQueries();
            Book bookList = b1.findByIsbn(isbnObject);
             LmsuserQueries userObject = new LmsuserQueries();
             Lmsuser userList = userObject.findByEmail(SessionService.getInstance());
            int userId = userList.getId();
            HoldBookFunctions hb = new HoldBookFunctions();
            hb.reserveBook(userId, bookList.getId());
             searchMessageLabel.setText("Book Reserved");
             searchMessageLabel.setVisible(true);
            
        } catch (Exception e) {

            searchMessageLabel.setText("Unable to hold book");
            searchMessageLabel.setVisible(true);

        }


    }//GEN-LAST:event_ReserveBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowerPage().setVisible(true);
            }
        });
    }

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));

    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {

        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));
        }

        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReserveBook;
    private javax.swing.JLabel addressPersonelInfo;
    private javax.swing.JTable borrowedBooksTable;
    private javax.swing.JPanel btn_1;
    private javax.swing.JPanel btn_2;
    private javax.swing.JPanel btn_3;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel cityPersonelInfo;
    private javax.swing.JLabel cnicPersonelInfo;
    private javax.swing.JPanel curr_1;
    private javax.swing.JPanel curr_2;
    private javax.swing.JPanel curr_3;
    private javax.swing.JLabel emailPersonelInfo;
    private javax.swing.JLabel genderPersonelInfo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable librariyanSearchBooksTable;
    private javax.swing.JLabel namePersonelInfo;
    private javax.swing.JPanel personelInfoPane;
    private javax.swing.JLabel phonePersonelInfo;
    private javax.swing.JButton searchBookButton;
    private javax.swing.JTextField searchBookLibrariyan;
    private javax.swing.JComboBox searchByCombo;
    private javax.swing.JLabel searchMessageLabel;
    private javax.swing.JPanel searchPane;
    // End of variables declaration//GEN-END:variables
}
