/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lms.userInterface;

import java.awt.Color;
import javax.swing.JPanel;

import com.lms.controllers.FineFunctions;
import com.lms.validation.*;
import com.lms.service.*;

import javax.persistence.Transient;
import javax.swing.ImageIcon;

/**
 *
 * @author wmall
 */
public class WelcomePage extends javax.swing.JFrame {

	@Transient
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form WelcomePage
	 */
	public WelcomePage() {
		initComponents();
		setColor(btn_1);
		curr_1.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_2, btn_4, btn_6, btn_5 },
				new JPanel[] { curr_2, curr_3, curr_4, curr_6, curr_5 });
		adminMessageLabel.setVisible(false);
		borrowerMessageLabel.setVisible(false);
		clerkMessageLabel.setVisible(false);
		librariyanMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(homePane);
		jPanel4.repaint();
		jPanel4.revalidate();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		btn_1 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		curr_1 = new javax.swing.JPanel();
		btn_3 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		curr_3 = new javax.swing.JPanel();
		btn_4 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		curr_4 = new javax.swing.JPanel();
		btn_6 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		curr_6 = new javax.swing.JPanel();
		btn_2 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		curr_2 = new javax.swing.JPanel();
		btn_5 = new javax.swing.JPanel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		curr_5 = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		btn_exit = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		homePane = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		adminLoginPane = new javax.swing.JPanel();
		jLabel33 = new javax.swing.JLabel();
		jLabel34 = new javax.swing.JLabel();
		emailAdminLogin = new javax.swing.JTextField();
		jLabel35 = new javax.swing.JLabel();
		passwordAdminLogin = new javax.swing.JPasswordField();
		adminLoginButton = new javax.swing.JButton();
		adminMessageLabel = new javax.swing.JLabel();
		librariyanLoginPane = new javax.swing.JPanel();
		jLabel30 = new javax.swing.JLabel();
		jLabel31 = new javax.swing.JLabel();
		emailLibrariyanLogin = new javax.swing.JTextField();
		jLabel32 = new javax.swing.JLabel();
		passwordLibrariyanLogin = new javax.swing.JPasswordField();
		librariyanLoginButton = new javax.swing.JButton();
		librariyanMessageLabel = new javax.swing.JLabel();
		borrowerLoginPane = new javax.swing.JPanel();
		jLabel24 = new javax.swing.JLabel();
		emailBorrowerLogin = new javax.swing.JTextField();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		passwordBorrowerLogin = new javax.swing.JPasswordField();
		borrowerLoginButton = new javax.swing.JButton();
		borrowerMessageLabel = new javax.swing.JLabel();
		checkOutClerkLoginPane = new javax.swing.JPanel();
		jLabel27 = new javax.swing.JLabel();
		jLabel28 = new javax.swing.JLabel();
		emailClerkLogin = new javax.swing.JTextField();
		jLabel29 = new javax.swing.JLabel();
		passwordClerkLogin = new javax.swing.JPasswordField();
		clerkLoginButton = new javax.swing.JButton();
		clerkMessageLabel = new javax.swing.JLabel();
		totalFinePane = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		printOverduesLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel3.setBackground(new java.awt.Color(0, 37, 63));
		jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		btn_1.setBackground(new java.awt.Color(0, 37, 45));
		btn_1.setForeground(new java.awt.Color(255, 255, 255));
		btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_1MousePressed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel7.setForeground(new java.awt.Color(255, 255, 255));
		jLabel7.setText("Home");

		jLabel8.setIcon(new ImageIcon(WelcomePage.class.getResource("/com/lms/images/Library_25px.png"))); // NOI18N

		curr_1.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_1Layout = new javax.swing.GroupLayout(curr_1);
		curr_1.setLayout(curr_1Layout);
		curr_1Layout.setHorizontalGroup(curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_1Layout.setVerticalGroup(curr_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
		btn_1.setLayout(btn_1Layout);
		btn_1Layout
				.setHorizontalGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_1Layout.createSequentialGroup()
								.addComponent(curr_1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel8).addGap(18, 18, 18).addComponent(jLabel7)
								.addContainerGap(187, Short.MAX_VALUE)));
		btn_1Layout.setVerticalGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_1Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel8).addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 60));

		btn_3.setBackground(new java.awt.Color(0, 37, 45));
		btn_3.setForeground(new java.awt.Color(255, 255, 255));
		btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_3MousePressed(evt);
			}
		});

		jLabel9.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(255, 255, 255));
		jLabel9.setText("Librariyan Login");

		jLabel10.setIcon(new ImageIcon(WelcomePage.class.getResource("/com/lms/images/Manager_25px.png"))); // NOI18N

		curr_3.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_3Layout = new javax.swing.GroupLayout(curr_3);
		curr_3.setLayout(curr_3Layout);
		curr_3Layout.setHorizontalGroup(curr_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_3Layout.setVerticalGroup(curr_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
		btn_3.setLayout(btn_3Layout);
		btn_3Layout
				.setHorizontalGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_3Layout.createSequentialGroup()
								.addComponent(curr_3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel10)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel9).addContainerGap(115, Short.MAX_VALUE)));
		btn_3Layout.setVerticalGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_3Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel10).addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 60));

		btn_4.setBackground(new java.awt.Color(0, 37, 45));
		btn_4.setForeground(new java.awt.Color(255, 255, 255));
		btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_4MousePressed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel11.setForeground(new java.awt.Color(255, 255, 255));
		jLabel11.setText("Borrower Login");

		jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/User_25px.png"))); // NOI18N

		curr_4.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_4Layout = new javax.swing.GroupLayout(curr_4);
		curr_4.setLayout(curr_4Layout);
		curr_4Layout.setHorizontalGroup(curr_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_4Layout.setVerticalGroup(curr_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
		btn_4.setLayout(btn_4Layout);
		btn_4Layout
				.setHorizontalGroup(btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_4Layout.createSequentialGroup()
								.addComponent(curr_4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel12)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel11).addContainerGap(118, Short.MAX_VALUE)));
		btn_4Layout.setVerticalGroup(btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_4Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel12).addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 60));

		btn_6.setBackground(new java.awt.Color(0, 37, 45));
		btn_6.setForeground(new java.awt.Color(255, 255, 255));
		btn_6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_6MousePressed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel13.setForeground(new java.awt.Color(255, 255, 255));
		jLabel13.setText("Check Total Overdues Paid");

		jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Cash _25px.png"))); // NOI18N

		curr_6.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_6Layout = new javax.swing.GroupLayout(curr_6);
		curr_6.setLayout(curr_6Layout);
		curr_6Layout.setHorizontalGroup(curr_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_6Layout.setVerticalGroup(curr_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_6Layout = new javax.swing.GroupLayout(btn_6);
		btn_6.setLayout(btn_6Layout);
		btn_6Layout
				.setHorizontalGroup(btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_6Layout.createSequentialGroup()
								.addComponent(curr_6, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel14)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel13).addContainerGap(45, Short.MAX_VALUE)));
		btn_6Layout.setVerticalGroup(btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_6Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel14).addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 290, 60));

		btn_2.setBackground(new java.awt.Color(0, 37, 45));
		btn_2.setForeground(new java.awt.Color(255, 255, 255));
		btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_2MousePressed(evt);
			}
		});

		jLabel15.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel15.setForeground(new java.awt.Color(255, 255, 255));
		jLabel15.setText("Admin Login");

		jLabel16.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Database Administrator_25px.png"))); // NOI18N

		curr_2.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_2Layout = new javax.swing.GroupLayout(curr_2);
		curr_2.setLayout(curr_2Layout);
		curr_2Layout.setHorizontalGroup(curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_2Layout.setVerticalGroup(curr_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
		btn_2.setLayout(btn_2Layout);
		btn_2Layout
				.setHorizontalGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_2Layout.createSequentialGroup()
								.addComponent(curr_2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel16).addGap(18, 18, 18).addComponent(jLabel15)
								.addContainerGap(142, Short.MAX_VALUE)));
		btn_2Layout.setVerticalGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_2Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel16).addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 290, 60));

		btn_5.setBackground(new java.awt.Color(0, 37, 45));
		btn_5.setForeground(new java.awt.Color(255, 255, 255));
		btn_5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_5MousePressed(evt);
			}
		});

		jLabel18.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		jLabel18.setForeground(new java.awt.Color(255, 255, 255));
		jLabel18.setText("Check Out Clerk Login");

		jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Front Desk_25px.png"))); // NOI18N

		curr_5.setPreferredSize(new java.awt.Dimension(5, 0));

		javax.swing.GroupLayout curr_5Layout = new javax.swing.GroupLayout(curr_5);
		curr_5.setLayout(curr_5Layout);
		curr_5Layout.setHorizontalGroup(curr_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 5, Short.MAX_VALUE));
		curr_5Layout.setVerticalGroup(curr_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout btn_5Layout = new javax.swing.GroupLayout(btn_5);
		btn_5.setLayout(btn_5Layout);
		btn_5Layout
				.setHorizontalGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_5Layout.createSequentialGroup()
								.addComponent(curr_5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel19)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel18).addContainerGap(81, Short.MAX_VALUE)));
		btn_5Layout.setVerticalGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(curr_5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
				.addGroup(btn_5Layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(btn_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel19).addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE,
										25, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(0, 15, Short.MAX_VALUE)));

		jPanel3.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 60));

		getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 620));

		jPanel1.setBackground(new java.awt.Color(2, 91, 131));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel2.setBackground(new java.awt.Color(2, 91, 110));
		jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				jPanel2MouseDragged(evt);
			}
		});
		jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jPanel2MousePressed(evt);
			}
		});

		btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/Cancel_22px.png"))); // NOI18N
		btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				btn_exitMousePressed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(748, Short.MAX_VALUE).addComponent(btn_exit).addContainerGap()));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btn_exit).addContainerGap()));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

		jPanel4.setBackground(new java.awt.Color(0, 37, 63));
		jPanel4.setLayout(new java.awt.CardLayout());

		homePane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lms/images/search_256px.png"))); // NOI18N

		jLabel2.setFont(new java.awt.Font("SketchFlow Print", 0, 36)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Welcome to LMS");

		jLabel3.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Bad libraries build collections, good libraries build services,");

		jLabel4.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("great libraries build communities.");

		jLabel17.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel17.setForeground(new java.awt.Color(255, 255, 255));
		jLabel17.setText("–R. David Lankes");

		javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
		homePane.setLayout(homePaneLayout);
		homePaneLayout.setHorizontalGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(homePaneLayout.createSequentialGroup().addGroup(homePaneLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(homePaneLayout.createSequentialGroup().addGap(245, 245, 245)
								.addGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 413,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1)))
						.addGroup(homePaneLayout.createSequentialGroup().addGap(137, 137, 137).addComponent(jLabel3))
						.addGroup(homePaneLayout.createSequentialGroup().addGap(244, 244, 244).addComponent(jLabel4))
						.addGroup(homePaneLayout.createSequentialGroup().addGap(315, 315, 315).addComponent(jLabel17,
								javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(455, Short.MAX_VALUE)));
		homePaneLayout.setVerticalGroup(homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(homePaneLayout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(42, 42, 42).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel17)
						.addContainerGap(133, Short.MAX_VALUE)));

		jPanel4.add(homePane, "card2");

		adminLoginPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel33.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
		jLabel33.setForeground(new java.awt.Color(255, 255, 255));
		jLabel33.setText("Administrator Login");

		jLabel34.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel34.setForeground(new java.awt.Color(255, 255, 255));
		jLabel34.setText("Email  :");

		emailAdminLogin.setBackground(new java.awt.Color(2, 91, 133));
		emailAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
		emailAdminLogin.setToolTipText("");
		emailAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		emailAdminLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailAdminLoginActionPerformed(evt);
			}
		});

		jLabel35.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel35.setForeground(new java.awt.Color(255, 255, 255));
		jLabel35.setText("Password  :");

		passwordAdminLogin.setBackground(new java.awt.Color(2, 91, 133));
		passwordAdminLogin.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
		passwordAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
		passwordAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

		adminLoginButton.setBackground(new java.awt.Color(2, 91, 133));
		adminLoginButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		adminLoginButton.setForeground(new java.awt.Color(255, 255, 255));
		adminLoginButton.setText("Login");
		adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adminLoginButtonActionPerformed(evt);
			}
		});

		adminMessageLabel.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
		adminMessageLabel.setForeground(new java.awt.Color(255, 51, 51));
		adminMessageLabel.setText("jLabel39");

		javax.swing.GroupLayout adminLoginPaneLayout = new javax.swing.GroupLayout(adminLoginPane);
		adminLoginPane.setLayout(adminLoginPaneLayout);
		adminLoginPaneLayout.setHorizontalGroup(adminLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(adminLoginPaneLayout.createSequentialGroup().addContainerGap(161, Short.MAX_VALUE).addGroup(
						adminLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								adminLoginPaneLayout.createSequentialGroup()
										.addComponent(adminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(235, 235, 235))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										adminLoginPaneLayout.createSequentialGroup().addComponent(jLabel33).addGap(135,
												135, 135))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										adminLoginPaneLayout.createSequentialGroup().addGroup(adminLoginPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(adminMessageLabel)
												.addGroup(adminLoginPaneLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(adminLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel34)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(emailAdminLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(adminLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel35).addGap(18, 18, 18)
																.addComponent(passwordAdminLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGap(193, 193, 193)))));
		adminLoginPaneLayout.setVerticalGroup(adminLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(adminLoginPaneLayout.createSequentialGroup().addGap(69, 69, 69).addComponent(jLabel33)
						.addGap(18, 18, 18).addComponent(adminMessageLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addGroup(adminLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(emailAdminLogin, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(50, 50, 50)
						.addGroup(adminLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel35))
						.addGap(58, 58, 58).addComponent(adminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(180, 180, 180)));

		jPanel4.add(adminLoginPane, "card2");

		librariyanLoginPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel30.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
		jLabel30.setForeground(new java.awt.Color(255, 255, 255));
		jLabel30.setText("Librariyan Login");

		jLabel31.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel31.setForeground(new java.awt.Color(255, 255, 255));
		jLabel31.setText("Email  :");

		emailLibrariyanLogin.setBackground(new java.awt.Color(2, 91, 133));
		emailLibrariyanLogin.setForeground(new java.awt.Color(255, 255, 255));
		emailLibrariyanLogin.setToolTipText("");
		emailLibrariyanLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		emailLibrariyanLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailLibrariyanLoginActionPerformed(evt);
			}
		});

		jLabel32.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel32.setForeground(new java.awt.Color(255, 255, 255));
		jLabel32.setText("Password  :");

		passwordLibrariyanLogin.setBackground(new java.awt.Color(2, 91, 133));
		passwordLibrariyanLogin.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
		passwordLibrariyanLogin.setForeground(new java.awt.Color(255, 255, 255));
		passwordLibrariyanLogin
				.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

		librariyanLoginButton.setBackground(new java.awt.Color(2, 91, 133));
		librariyanLoginButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		librariyanLoginButton.setForeground(new java.awt.Color(255, 255, 255));
		librariyanLoginButton.setText("Login");
		librariyanLoginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				librariyanLoginButtonActionPerformed(evt);
			}
		});

		librariyanMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		librariyanMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
		librariyanMessageLabel.setText("jLabel39");

		javax.swing.GroupLayout librariyanLoginPaneLayout = new javax.swing.GroupLayout(librariyanLoginPane);
		librariyanLoginPane.setLayout(librariyanLoginPaneLayout);
		librariyanLoginPaneLayout.setHorizontalGroup(librariyanLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librariyanLoginPaneLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(librariyanLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librariyanLoginPaneLayout
										.createSequentialGroup()
										.addComponent(librariyanLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE,
												289, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(235, 235, 235))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, librariyanLoginPaneLayout
										.createSequentialGroup()
										.addGroup(librariyanLoginPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(librariyanMessageLabel)
												.addGroup(librariyanLoginPaneLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(librariyanLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel31)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(emailLibrariyanLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(librariyanLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel32).addGap(18, 18, 18)
																.addComponent(passwordLibrariyanLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(193, 193, 193))))
				.addGroup(librariyanLoginPaneLayout.createSequentialGroup().addGap(192, 192, 192).addComponent(jLabel30)
						.addContainerGap(188, Short.MAX_VALUE)));
		librariyanLoginPaneLayout.setVerticalGroup(librariyanLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(librariyanLoginPaneLayout.createSequentialGroup().addGap(69, 69, 69).addComponent(jLabel30)
						.addGap(18, 18, 18).addComponent(librariyanMessageLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
						.addGroup(
								librariyanLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(emailLibrariyanLogin, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(50, 50, 50)
						.addGroup(librariyanLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordLibrariyanLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel32))
						.addGap(58, 58, 58).addComponent(librariyanLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE,
								39, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(180, 180, 180)));

		jPanel4.add(librariyanLoginPane, "card2");

		borrowerLoginPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel24.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
		jLabel24.setForeground(new java.awt.Color(255, 255, 255));
		jLabel24.setText("Borrower Login");

		emailBorrowerLogin.setBackground(new java.awt.Color(2, 91, 133));
		emailBorrowerLogin.setForeground(new java.awt.Color(255, 255, 255));
		emailBorrowerLogin.setToolTipText("");
		emailBorrowerLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		emailBorrowerLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailBorrowerLoginActionPerformed(evt);
			}
		});

		jLabel25.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel25.setForeground(new java.awt.Color(255, 255, 255));
		jLabel25.setText("Email  :");

		jLabel26.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel26.setForeground(new java.awt.Color(255, 255, 255));
		jLabel26.setText("Password  :");

		passwordBorrowerLogin.setBackground(new java.awt.Color(2, 91, 133));
		passwordBorrowerLogin.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
		passwordBorrowerLogin.setForeground(new java.awt.Color(255, 255, 255));
		passwordBorrowerLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

		borrowerLoginButton.setBackground(new java.awt.Color(2, 91, 133));
		borrowerLoginButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		borrowerLoginButton.setForeground(new java.awt.Color(255, 255, 255));
		borrowerLoginButton.setText("Login");
		borrowerLoginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				borrowerLoginButtonActionPerformed(evt);
			}
		});

		borrowerMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		borrowerMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
		borrowerMessageLabel.setText("jLabel39");

		javax.swing.GroupLayout borrowerLoginPaneLayout = new javax.swing.GroupLayout(borrowerLoginPane);
		borrowerLoginPane.setLayout(borrowerLoginPaneLayout);
		borrowerLoginPaneLayout.setHorizontalGroup(borrowerLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowerLoginPaneLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(borrowerLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrowerLoginPaneLayout
										.createSequentialGroup()
										.addComponent(borrowerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(235, 235, 235))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										borrowerLoginPaneLayout.createSequentialGroup().addGroup(borrowerLoginPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(borrowerLoginPaneLayout.createSequentialGroup()
														.addComponent(jLabel25)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(emailBorrowerLogin,
																javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(borrowerLoginPaneLayout.createSequentialGroup()
														.addComponent(jLabel26).addGap(18, 18, 18)
														.addComponent(passwordBorrowerLogin,
																javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(193, 193, 193))))
				.addGroup(borrowerLoginPaneLayout.createSequentialGroup()
						.addGroup(borrowerLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(borrowerLoginPaneLayout.createSequentialGroup().addGap(192, 192, 192)
										.addComponent(jLabel24))
								.addGroup(borrowerLoginPaneLayout.createSequentialGroup().addGap(220, 220, 220)
										.addComponent(borrowerMessageLabel)))
						.addContainerGap(201, Short.MAX_VALUE)));
		borrowerLoginPaneLayout.setVerticalGroup(borrowerLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(borrowerLoginPaneLayout.createSequentialGroup().addGap(69, 69, 69).addComponent(jLabel24)
						.addGap(18, 18, 18).addComponent(borrowerMessageLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
						.addGroup(borrowerLoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(emailBorrowerLogin, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(50, 50, 50)
						.addGroup(borrowerLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordBorrowerLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel26))
						.addGap(58, 58, 58).addComponent(borrowerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE,
								39, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(180, 180, 180)));

		jPanel4.add(borrowerLoginPane, "card2");

		checkOutClerkLoginPane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel27.setFont(new java.awt.Font("SketchFlow Print", 0, 48)); // NOI18N
		jLabel27.setForeground(new java.awt.Color(255, 255, 255));
		jLabel27.setText("Check Out Clerk Login");

		jLabel28.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel28.setForeground(new java.awt.Color(255, 255, 255));
		jLabel28.setText("Email  :");

		emailClerkLogin.setBackground(new java.awt.Color(2, 91, 133));
		emailClerkLogin.setForeground(new java.awt.Color(255, 255, 255));
		emailClerkLogin.setToolTipText("");
		emailClerkLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
		emailClerkLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				//emailClerkLoginActionPerformed(evt);
			}
		});

		jLabel29.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		jLabel29.setForeground(new java.awt.Color(255, 255, 255));
		jLabel29.setText("Password  :");

		passwordClerkLogin.setBackground(new java.awt.Color(2, 91, 133));
		passwordClerkLogin.setFont(new java.awt.Font("SketchFlow Print", 0, 18)); // NOI18N
		passwordClerkLogin.setForeground(new java.awt.Color(255, 255, 255));
		passwordClerkLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

		clerkLoginButton.setBackground(new java.awt.Color(2, 91, 133));
		clerkLoginButton.setFont(new java.awt.Font("SketchFlow Print", 2, 18)); // NOI18N
		clerkLoginButton.setForeground(new java.awt.Color(255, 255, 255));
		clerkLoginButton.setText("Login");
		clerkLoginButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				clerkLoginButtonActionPerformed(evt);
			}
		});

		clerkMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
		clerkMessageLabel.setForeground(new java.awt.Color(255, 0, 51));
		clerkMessageLabel.setText("jLabel39");

		javax.swing.GroupLayout checkOutClerkLoginPaneLayout = new javax.swing.GroupLayout(checkOutClerkLoginPane);
		checkOutClerkLoginPane.setLayout(checkOutClerkLoginPaneLayout);
		checkOutClerkLoginPaneLayout.setHorizontalGroup(checkOutClerkLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(checkOutClerkLoginPaneLayout.createSequentialGroup().addContainerGap(137, Short.MAX_VALUE)
						.addGroup(checkOutClerkLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										checkOutClerkLoginPaneLayout.createSequentialGroup()
												.addComponent(clerkLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE,
														289, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(235, 235, 235))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										checkOutClerkLoginPaneLayout.createSequentialGroup().addComponent(jLabel27)
												.addGap(118, 118, 118))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkOutClerkLoginPaneLayout
										.createSequentialGroup()
										.addGroup(checkOutClerkLoginPaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(clerkMessageLabel)
												.addGroup(checkOutClerkLoginPaneLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(checkOutClerkLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel28)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(emailClerkLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(checkOutClerkLoginPaneLayout.createSequentialGroup()
																.addComponent(jLabel29).addGap(18, 18, 18)
																.addComponent(passwordClerkLogin,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 245,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(193, 193, 193)))));
		checkOutClerkLoginPaneLayout.setVerticalGroup(checkOutClerkLoginPaneLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(checkOutClerkLoginPaneLayout.createSequentialGroup().addGap(68, 68, 68).addComponent(jLabel27)
						.addGap(18, 18, 18).addComponent(clerkMessageLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addGroup(checkOutClerkLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(emailClerkLogin, javax.swing.GroupLayout.Alignment.TRAILING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 26,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING))
						.addGap(50, 50, 50)
						.addGroup(checkOutClerkLoginPaneLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordClerkLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel29))
						.addGap(58, 58, 58).addComponent(clerkLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(180, 180, 180)));

		jPanel4.add(checkOutClerkLoginPane, "card2");

		totalFinePane.setBackground(new java.awt.Color(2, 91, 133));

		jLabel23.setFont(new java.awt.Font("SketchFlow Print", 0, 36)); // NOI18N
		jLabel23.setForeground(new java.awt.Color(255, 255, 255));
		jLabel23.setText("Total Overdues Paid");

		printOverduesLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
		printOverduesLabel.setForeground(new java.awt.Color(255, 255, 255));
		printOverduesLabel.setText("jLabel36");

		javax.swing.GroupLayout totalFinePaneLayout = new javax.swing.GroupLayout(totalFinePane);
		totalFinePane.setLayout(totalFinePaneLayout);
		totalFinePaneLayout
				.setHorizontalGroup(totalFinePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								totalFinePaneLayout.createSequentialGroup().addContainerGap(207, Short.MAX_VALUE)
										.addGroup(totalFinePaneLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(printOverduesLabel).addComponent(jLabel23))
										.addGap(205, 205, 205)));
		totalFinePaneLayout
				.setVerticalGroup(totalFinePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(totalFinePaneLayout.createSequentialGroup().addGap(53, 53, 53).addComponent(jLabel23)
								.addGap(156, 156, 156).addComponent(printOverduesLabel)
								.addContainerGap(291, Short.MAX_VALUE)));

		jPanel4.add(totalFinePane, "card2");

		jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 580));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 780, 620));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	int xx, xy;

	private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel2MouseDragged
		// TODO add your handling code here:

		// source to drag
		int x = evt.getXOnScreen();
		int y = evt.getYOnScreen();
		this.setLocation(x - xx, y - xy);
	}// GEN-LAST:event_jPanel2MouseDragged

	private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel2MousePressed
		// TODO add your handling code here:

		// drag this pane
		xx = evt.getX();
		xy = evt.getY();
	}// GEN-LAST:event_jPanel2MousePressed

	private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_exitMousePressed
		// TODO add your handling code here:
		// exit button
		System.exit(0);
	}// GEN-LAST:event_btn_exitMousePressed

	private void btn_1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_1MousePressed
		// TODO add your handling code here:

		setColor(btn_1);
		curr_1.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_2, btn_4, btn_5, btn_6 },
				new JPanel[] { curr_2, curr_3, curr_4, curr_5, curr_6 });

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(homePane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_1MousePressed

	private void btn_3MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_3MousePressed
		// TODO add your handling code here:

		setColor(btn_3);
		curr_3.setOpaque(true);
		resetColor(new JPanel[] { btn_1, btn_2, btn_4, btn_6, btn_5 },
				new JPanel[] { curr_1, curr_2, curr_4, curr_6, curr_5 });
		librariyanMessageLabel.setVisible(false);
		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(librariyanLoginPane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_3MousePressed

	private void btn_4MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_4MousePressed
		// TODO add your handling code here:

		setColor(btn_4);
		curr_4.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_1, btn_2, btn_6, btn_5 },
				new JPanel[] { curr_3, curr_1, curr_2, curr_5, curr_6 });
		borrowerMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(borrowerLoginPane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_4MousePressed

	private void btn_6MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_6MousePressed
		// TODO add your handling code here:

		setColor(btn_6);
		curr_6.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_4, btn_1, btn_5, btn_2 },
				new JPanel[] { curr_3, curr_4, curr_1, curr_2, curr_5 });

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(totalFinePane);
		jPanel4.repaint();
		jPanel4.revalidate();

		FineFunctions f1 = new FineFunctions();
		String totalFine = f1.calculateTotalFine();
		if (totalFine == null) {
			printOverduesLabel.setText("Rs : " + "0");
		} else {
			printOverduesLabel.setText("Rs : " + totalFine);
		}

	}// GEN-LAST:event_btn_6MousePressed

	private void btn_2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_2MousePressed
		// TODO add your handling code here:
		setColor(btn_2);
		curr_2.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_4, btn_1, btn_6, btn_5 },
				new JPanel[] { curr_3, curr_4, curr_1, curr_5, curr_6 });
		adminMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(adminLoginPane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_2MousePressed

	private void borrowerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_borrowerLoginButtonActionPerformed

		String email = null;
		char[] password = null;
		try {
			email = emailBorrowerLogin.getText();
			password = passwordBorrowerLogin.getPassword();
			String pass = new String(password);

			String msg = InputValidation.loginValidate(email, pass);
			if (!msg.equals("1")) {
				borrowerMessageLabel.setText("Please write Your email");
				borrowerMessageLabel.setVisible(true);
				return;
			}

			if (!EmailValidation.validate(email)) {
				borrowerMessageLabel.setText("Please write valid email");
				borrowerMessageLabel.setVisible(true);
				return;
			}

			msg = LoginValidation.validateBorrower(email, pass);

			if (!msg.equals("1")) {

				borrowerMessageLabel.setText(msg);
				borrowerMessageLabel.setVisible(true);
				return;
			}

			borrowerMessageLabel.setText("Sending Confirmation email...");
			borrowerMessageLabel.setVisible(true);

			String subject = "LMS Borrower Login Confirmation";
			String message = "You have logged In on LMS.If it were not you please contact Librariyan";

			confirmationMail(email, subject, message);

			SessionService.setInstance(email);

			this.dispose();
			new BorrowerPage().setVisible(true);

		} catch (Exception e) {

			borrowerMessageLabel.setText("Unable to Login");
			borrowerMessageLabel.setVisible(true);

		}

	}// GEN-LAST:event_borrowerLoginButtonActionPerformed

	private void clerkLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clerkLoginButtonActionPerformed

		String email = null;
		char[] password = null;
		try {
			email = emailClerkLogin.getText();
			password = passwordClerkLogin.getPassword();
			String pass = new String(password);

			String msg = InputValidation.loginValidate(email, pass);
			if (!msg.equals("1")) {
				clerkMessageLabel.setText("Please write Your email");
				clerkMessageLabel.setVisible(true);
				return;
			}

			if (!EmailValidation.validate(email)) {
				clerkMessageLabel.setText("Please write valid email");
				clerkMessageLabel.setVisible(true);
				return;
			}

			msg = LoginValidation.validateClerk(email, pass);

			if (!msg.equals("1")) {

				clerkMessageLabel.setText(msg);
				clerkMessageLabel.setVisible(true);
				return;
			}

			clerkMessageLabel.setText("Sending Confirmation Email...");
			clerkMessageLabel.setVisible(true);

			String subject = "Check Out Clerk Login Confirmation";
			String message = "You have logged In on LMS.If it were not you please contact Librariyan";

			confirmationMail(email, subject, message);

			SessionService.setInstance(email);

			this.dispose();
			new CheckOutClerk().setVisible(true);

		} catch (Exception e) {

			clerkMessageLabel.setText("Unable to Login");
			clerkMessageLabel.setVisible(true);

		}

	}// GEN-LAST:event_clerkLoginButtonActionPerformed

	private void librariyanLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_librariyanLoginButtonActionPerformed

		String email = null;
		char[] password = null;
		try {
			email = emailLibrariyanLogin.getText();
			password = passwordLibrariyanLogin.getPassword();
			String pass = new String(password);

			String msg = InputValidation.loginValidate(email, pass);
			if (!msg.equals("1")) {
				librariyanMessageLabel.setText("Please write Your email");
				librariyanMessageLabel.setVisible(true);
				return;
			}

			if (!EmailValidation.validate(email)) {
				librariyanMessageLabel.setText("Please write valid email");
				librariyanMessageLabel.setVisible(true);
				return;
			}

			msg = LoginValidation.validateLibrariyan(email, pass);

			if (!msg.equals("1")) {

				librariyanMessageLabel.setText(msg);
				librariyanMessageLabel.setVisible(true);
				return;
			}

			librariyanMessageLabel.setText("Sending Confirmation Email...");
			librariyanMessageLabel.setVisible(true);

			String subject = "Librariyan Login Confirmation";
			String message = "You have logged In on LMS.If it were not you please contact Admin";

			confirmationMail(email, subject, message);

			SessionService.setInstance(email);

			this.dispose();
			new AdminPage().setVisible(true);

		} catch (Exception e) {

			librariyanMessageLabel.setText("Unable to Login");
			librariyanMessageLabel.setVisible(true);

		}

	}// GEN-LAST:event_librariyanLoginButtonActionPerformed

	public void confirmationMail(String to, String subject, String message) {

		String user = "xyz@gmail.com";  // add your mail here
		String passwordEmail = "xyz"; // add your correct password here

		SendMail.send(to, subject, message, user, passwordEmail);

	}

	private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adminLoginButtonActionPerformed
		String email = null;
		char[] password = null;
		try {
			email = emailAdminLogin.getText();
			password = passwordAdminLogin.getPassword();
			String pass = new String(password);

			String msg = InputValidation.loginValidate(email, pass);
			if (!msg.equals("1")) {
				adminMessageLabel.setText("Please write Your email");
				adminMessageLabel.setVisible(true);
				return;
			}

			if (!EmailValidation.validate(email)) {
				adminMessageLabel.setText("Please write valid email");
				adminMessageLabel.setVisible(true);
				return;
			}

			msg = LoginValidation.validateAdmin(email, pass);

			if (!msg.equals("1")) {

				adminMessageLabel.setText(msg);
				adminMessageLabel.setVisible(true);
				return;
			}

			adminMessageLabel.setText("Sending Confirmation Email...");
			adminMessageLabel.setVisible(true);

			String subject = "LMS Admin Login Confirmation";
			String message = "You have logged In on LMS.If it were not you please take action";

			confirmationMail(email, subject, message);

			SessionService.setInstance(email);

			this.dispose();
			new AdminPage().setVisible(true);

		} catch (Exception e) {

			adminMessageLabel.setText("Unable to Login");
			adminMessageLabel.setVisible(true);

		}
	}// GEN-LAST:event_adminLoginButtonActionPerformed

	private void btn_5MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_5MousePressed

		setColor(btn_5);
		curr_5.setOpaque(true);
		resetColor(new JPanel[] { btn_3, btn_4, btn_1, btn_2, btn_6 },
				new JPanel[] { curr_3, curr_4, curr_1, curr_2, curr_6 });
		clerkMessageLabel.setVisible(false);

		jPanel4.removeAll();
		jPanel4.repaint();
		jPanel4.revalidate();

		jPanel4.add(checkOutClerkLoginPane);
		jPanel4.repaint();
		jPanel4.revalidate();

	}// GEN-LAST:event_btn_5MousePressed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new WelcomePage().setVisible(true);
			}
		});
	}

	private void setColor(JPanel pane) {
		pane.setBackground(new Color(41, 57, 80));

	}

	private void resetColor(JPanel[] pane, JPanel[] indicators) {

		for (int i = 0; i < pane.length; i++) {
			pane[i].setBackground(new Color(23, 35, 51));
		}

		for (int i = 0; i < indicators.length; i++) {
			indicators[i].setOpaque(false);
		}

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton adminLoginButton;
	private javax.swing.JPanel adminLoginPane;
	private javax.swing.JLabel adminMessageLabel;
	private javax.swing.JButton borrowerLoginButton;
	private javax.swing.JPanel borrowerLoginPane;
	private javax.swing.JLabel borrowerMessageLabel;
	private javax.swing.JPanel btn_1;
	private javax.swing.JPanel btn_2;
	private javax.swing.JPanel btn_3;
	private javax.swing.JPanel btn_4;
	private javax.swing.JPanel btn_5;
	private javax.swing.JPanel btn_6;
	private javax.swing.JLabel btn_exit;
	private javax.swing.JPanel checkOutClerkLoginPane;
	private javax.swing.JButton clerkLoginButton;
	private javax.swing.JLabel clerkMessageLabel;
	private javax.swing.JPanel curr_1;
	private javax.swing.JPanel curr_2;
	private javax.swing.JPanel curr_3;
	private javax.swing.JPanel curr_4;
	private javax.swing.JPanel curr_5;
	private javax.swing.JPanel curr_6;
	private javax.swing.JTextField emailAdminLogin;
	private javax.swing.JTextField emailBorrowerLogin;
	private javax.swing.JTextField emailClerkLogin;
	private javax.swing.JTextField emailLibrariyanLogin;
	private javax.swing.JPanel homePane;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JButton librariyanLoginButton;
	private javax.swing.JPanel librariyanLoginPane;
	private javax.swing.JLabel librariyanMessageLabel;
	private javax.swing.JPasswordField passwordAdminLogin;
	private javax.swing.JPasswordField passwordBorrowerLogin;
	private javax.swing.JPasswordField passwordClerkLogin;
	private javax.swing.JPasswordField passwordLibrariyanLogin;
	private javax.swing.JLabel printOverduesLabel;
	private javax.swing.JPanel totalFinePane;
	// End of variables declaration//GEN-END:variables
}
